//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footwear
    {
        public int FootwearID { get; set; }
        public string FootwearCetogory { get; set; }
        public string FootwearType { get; set; }
        public string FootwearBrand { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
